name: schedule bu generator

on:
  schedule:
    - cron: '15 1 1 * *'
    - cron: '15 1 6 * *'
    - cron: '15 1 11 * *'
    - cron: '15 1 16 * *'
    - cron: '15 1 21 * *'
    - cron: '15 1 26 * *'
    
  workflow_dispatch: 

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: install env
        id: my_env
        run: |
          sudo apt-get install -y libssl-dev libboost-all-dev
          git config --global user.name "buinpdf"
          git config --global user.email "buinpdf@atomicmail.io"
          echo "year=$(date +%Y)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4

      - name: build cpp proj
        run: |
          cd $GITHUB_WORKSPACE
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          mkdir build/bu_crawler_cache

      - name: restore Cache
        uses: actions/cache/restore@v5
        with:
          key: ${{ runner.os }}_bu_crawler_cache
          path: ${{github.workspace}}/build/bu_crawler_cache
        
      - name: download doc
        id: dl
        working-directory: build
        run: |
          echo "ldate=$(./bu_crawler ${{steps.my_env.outputs.year}} bu${{steps.my_env.outputs.year}}.html ca${{steps.my_env.outputs.year}}.html)" >> $GITHUB_OUTPUT

      - name: save Cache
        uses: actions/cache/save@v5
        with:
          key: ${{ runner.os }}_bu_crawler_cache
          path: ${{github.workspace}}/build/bu_crawler_cache

      - name: generate pdf
        working-directory: build
        run: |
          wget --no-verbose https://github.com/abramov7613/dompdfui/releases/download/v1.2.4/dompdfui_linux_x86_64.zip
          unzip dompdfui_linux_x86_64.zip > /dev/null
          ./dompdfui -m 1073741824 bu${{steps.my_env.outputs.year}}.html ca${{steps.my_env.outputs.year}}.html .
          
      - name: clone output repo
        id: cln
        working-directory: build
        run: |
          git clone https://github.com/buinpdf/download.git
          echo "current_bu=$(ls ./download/ | grep bu${{steps.my_env.outputs.year}})" >> $GITHUB_OUTPUT
        
      - name: prepare download repo
        if: contains(steps.cln.outputs.current_bu, 'pdf')
        working-directory: build/download
        run: |
          git remote set-url origin https://${{secrets.TOKEN}}@github.com/buinpdf/download.git
          git reset --hard HEAD~1
          git push origin main --force

      - name: save result
        working-directory: build
        run: |
          cp -f -t download bu${{steps.my_env.outputs.year}}.pdf ca${{steps.my_env.outputs.year}}.pdf
          cd ./download
          git remote set-url origin https://${{secrets.TOKEN}}@github.com/buinpdf/download.git
          git add .
          git commit -m "обновлено до ${{steps.dl.outputs.ldate}}"
          git push
          
