name: schedule bu generator

on:
  schedule:
  - cron: '50 19 24 * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: install env
      id: my_env
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libssl-dev git pkg-config wget libboost-all-dev
        echo "year=$(date +%Y)" >> $GITHUB_OUTPUT

    - uses: actions/checkout@v4

    - name: build cpp proj
      run: |
        cd $GITHUB_WORKSPACE
        cmake -S . -B build
        cmake --build build

    - name: generate doc
      id: gen
      run: |
        cd $GITHUB_WORKSPACE/build
        echo "ldate=$(./bu_crawler ${{steps.my_env.outputs.year}} bu${{steps.my_env.outputs.year}}.html ca${{steps.my_env.outputs.year}}.html)" >> $GITHUB_OUTPUT
        wget https://github.com/abramov7613/dompdfui/releases/download/v1.2.4/dompdfui_linux_x86_64.zip
        unzip dompdfui_linux_x86_64.zip
        ./dompdfui -m 1073741824 bu${{steps.my_env.outputs.year}}.html ca${{steps.my_env.outputs.year}}.html .

    - name: save in repo
      run: |
        cd $GITHUB_WORKSPACE/build
        git clone https://github.com/buinpdf/download.git
        cp -f -t download bu${{steps.my_env.outputs.year}}.pdf ca${{steps.my_env.outputs.year}}.pdf
        cd ./download
        git remote set-url origin https://${{secrets.TOKEN}}@github.com/buinpdf/download.git
        git add .
        git commit -m "обновлено до ${{steps.gen.outputs.ldate}}"
        git push
